spring.application.name=chatbot

#Porta do servidor
server.port=8080

#Conexao com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot
spring.datasource.username=postgres

#Altere o 1234 para a sua senha
spring.datasource.password=1234

#DDL - como o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.fail-on-unknown-properties=true


# Variavel ambiente do link da página
app.api.urlN8n=${http://localhost:5678/webhook-test/perguntar}

